You can use GitHub Actions to create a workflow that tests your R package on multiple operating systems. Here's an example of a GitHub Actions workflow YAML file that does that:

yaml

name: R package CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        r-version: [4.0]

    steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r-version }}

    - name: Install dependencies
      run: |
        R -e 'install.packages(c("remotes", "devtools")); remotes::install_deps(dependencies = TRUE)'

    - name: Check package
      run: R CMD check .

    - name: Build package
      run: R CMD build .
